# Generated by Django 5.1 on 2024-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='payment',
            field=models.CharField(choices=[('DONE', 'DONE'), ('NOT DONE', 'NOT DONE')], default='NOT DONE', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
