# Generated by Django 5.1 on 2024-08-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_school_student_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
