# Generated by Django 5.1 on 2024-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(related_name='batches', to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20),
        ),
    ]
