# Generated by Django 5.1 on 2024-08-16 12:56

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_batch_students_alter_batch_batch_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='N/A', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='class_level',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='max_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='room_location',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='batch',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
