# Generated by Django 5.1 on 2024-08-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_batch_batch_duration_batch_batch_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='room_location',
            new_name='class_mode',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_status',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='max_students',
        ),
    ]
