# Generated by Django 5.1 on 2024-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_room_location_batch_class_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='stream',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_duration',
            field=models.DurationField(default=''),
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_mode',
            field=models.CharField(default='Offline', max_length=100),
        ),
    ]
