# Generated by Django 5.1 on 2024-08-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_batch_stream_alter_batch_batch_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='stream',
        ),
    ]
