# Generated by Django 5.1 on 2024-08-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_stream_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='description',
        ),
    ]
