# Generated by Django 5.1 on 2024-08-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_stream_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
