# Generated by Django 5.1 on 2024-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(max_length=20),
        ),
    ]
