# Generated by Django 5.1 on 2024-08-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_batch_batch_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_duration',
            field=models.CharField(default='1hr', max_length=5),
        ),
    ]
