# Generated by Django 5.1 on 2024-08-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_batch_batch_day_alter_batch_batch_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_duration',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='teacher_name',
            field=models.CharField(max_length=100),
        ),
    ]
