# Generated by Django 5.1 on 2024-08-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_batch_batch_duration_alter_batch_class_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_duration',
        ),
    ]
