# Generated by Django 5.1 on 2024-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_batch_batch_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
