# Generated by Django 5.1 on 2024-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_student_name_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject_teaches', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
