# Generated by Django 5.1 on 2024-08-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_mode',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=100),
        ),
    ]
