# Generated by Django 5.1 on 2024-08-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_batch_class_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_mode',
            field=models.CharField(max_length=100),
        ),
    ]
