# Generated by Django 5.1 on 2024-08-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_alter_batch_class_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(related_name='batches', to='myapp.teacher'),
        ),
    ]
