# Generated by Django 5.1 on 2024-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_batch_teacher_name_batch_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(default=None, related_name='batches', to='myapp.teacher'),
        ),
    ]
