# Generated by Django 5.1 on 2024-08-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_alter_batch_students_alter_batch_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_level',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], max_length=50),
        ),
    ]
