# Generated by Django 5.1 on 2024-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_batch_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_day',
            field=models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THU', 'THURSDAY'), ('FRI', 'FRIDAY'), ('SAT', 'SATURDAY'), ('SUN', 'SUNDAY')], max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='batch',
            name='class_mode',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE')], default='ONLINE', max_length=100),
        ),
    ]
