# Generated by Django 5.1 on 2024-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_batch_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='myapp.student'),
        ),
    ]
