# Generated by Django 5.1 on 2024-08-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_alter_batch_batch_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.student'),
        ),
    ]
