# Generated by Django 5.1 on 2024-08-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='payment',
        ),
    ]
