# Generated by Django 5.1 on 2024-08-25 16:14

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_student_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.AddField(
            model_name='payment',
            name='months',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=[1], max_length=26),
        ),
    ]
