# Generated by Django 5.1 on 2024-08-30 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_phone_number', models.CharField(blank=True, max_length=15)),
                ('mother_phone_number', models.CharField(blank=True, max_length=15)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='myapp.student')),
            ],
        ),
    ]
