# Generated by Django 5.1 on 2024-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_parent_child_parent_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
