# Generated by Django 5.1 on 2024-08-30 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_student_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='addmission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
