# Generated by Django 5.1 on 2024-08-30 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_student_addmission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Std_Total_Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_due', to='myapp.student')),
            ],
        ),
    ]
