# Generated by Django 5.1 on 2024-08-30 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_std_total_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std_total_due',
            old_name='total_due',
            new_name='due',
        ),
    ]
