# Generated by Django 5.1 on 2024-08-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_rename_total_due_std_total_due_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std_total_due',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='total_due', to='myapp.student'),
        ),
    ]
