# Generated by Django 5.1 on 2024-08-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_alter_std_total_due_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Std_Total_Due',
            new_name='TotalDue',
        ),
    ]
