# Generated by Django 5.1 on 2024-08-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_totaldue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalDue',
        ),
    ]
