# Generated by Django 5.1 on 2024-08-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_delete_totaldue'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='modification',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
