# Generated by Django 5.1 on 2024-09-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_remove_batch_batch_time_batch_batch_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
    ]
