# Generated by Django 5.1 on 2024-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_remove_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
