# Generated by Django 5.1 on 2024-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_alter_teacher_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
